### ISSUE TITLE
fontObj is not a fontObj in pdf.js eval

### ISSUE THREAD

**Issue by rngadam** [modesty/pdf2json#104]
```
undefined:40950
            fontObj.spaceWidth = (spaceId >= 0 && isArray(fontObj.widths)) ? fontObj.widths[spaceId] : 250;
                               ^

TypeError: Cannot create property 'spaceWidth' on string 'Cannot read property '1' of undefined'
    at CanvasGraphics_setFont [as setFont] (eval at <anonymous> (/node_modules/pdf3json/lib/pdf.js:60:1), <anonymous>:40950:32)
    at CanvasGraphics_executeOperatorList [as executeOperatorList] (eval at <anonymous> (/node_modules/pdf3json/lib/pdf.js:60:1), <anonymous>:40560:27)
    at InternalRenderTask__next [as _next] (eval at <anonymous> (/node_modules/pdf3json/lib/pdf.js:60:1), <anonymous>:43553:39)
    at InternalRenderTask__continue [as _continue] (eval at <anonymous> (/node_modules/pdf3json/lib/pdf.js:60:1), <anonymous>:43545:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by luisskeeled** [comment]
Were you able to solve this issue?  I think I'm facing the same problem in my app currently.

**Comment by modesty** [comment]
which PDF ?
