### ISSUE TITLE
TypeError: Cannot set property 'get_id' of undefined

### ISSUE THREAD

**Issue by akashkumar2296** [modesty/pdf2json#146]
`/Users/kumarak/Documents/reaxt/Umich_schedule_planner/Ani-React-Theme/node_modules/pdf2json/pdfparser.js:96
        this.get_id = () => _id;
                    ^
TypeError: Cannot set property 'get_id' of undefined
    at PdfParser (/Users/kumarak/Documents/reaxt/Umich_schedule_planner/Ani-React-Theme/node_modules/pdf2json/pdfparser.js:96:21)
    at Object.<anonymous> (/Users/kumarak/Documents/reaxt/Umich_schedule_planner/Ani-React-Theme/build/webpack:/server.js:80:9)
    at __webpack_require__ (/Users/kumarak/Documents/reaxt/Umich_schedule_planner/Ani-React-Theme/build/webpack:/webpack/bootstrap 6116393c83e95f4fdfa2:25:1)
    at /Users/kumarak/Documents/reaxt/Umich_schedule_planner/Ani-React-Theme/build/webpack:/webpack/bootstrap 6116393c83e95f4fdfa2:60:1
    at Object.<anonymous> (/Users/kumarak/Documents/reaxt/Umich_schedule_planner/Ani-React-Theme/build/webpack:/webpack/bootstrap 6116393c83e95f4fdfa2:60:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
/Users/kumarak/Documents/reaxt/Umich_schedule_planner/Ani-React-Theme/tools/runServer.js:71
        throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);`

Not really sure why this error keeps popping up?

**Comment by modesty** [comment]
what is the PDF file?
