### ISSUE TITLE
On Node 10, "Callback must be a function"

### ISSUE THREAD

**Issue by pedrohugorm** [modesty/pdf2json#169]
The code:

```
const fs = require("fs");
const PDFParser = require("pdf2json");

const express = require("express");
import {Request, Response} from "express";

const router = express.Router();

/* GET home page. */
router.get("/", async (req: Request, res: Response, next: (...params) => void) => {

	const pdfParser = new PDFParser();

	pdfParser.on("pdfParser_dataError", (errData) => {
		console.error(errData.parserError);

		res.json(errData.parserError);
	});
	pdfParser.on("pdfParser_dataReady", (pdfData) => {
		fs.writeFile("./F1040EZ.json", JSON.stringify(pdfData));

		res.json(pdfData);
	});

	pdfParser.loadPDF("./SomePDF.pdf");
});

export default router;
```

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1132:14)
    at PdfParser.<anonymous> (/.../routes/index.js:24:12)
    at PdfParser.emit (events.js:182:13)
    at PdfParser._onPDFJSParseDataReady (/.../node_modules/pdf2json/pdfparser.js:23:9)
    at cls.emit (events.js:182:13)
    at process.nextTick (/.../node_modules/pdf2json/lib/pdf.js:250:38)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by joshuawootonn** [comment]
Any update on what the cause/resolution was for this error? Getting it too right now.

**Comment by pedrohugorm** [comment]
I closed it because it was actually a mistake on my side - the code expects an actual function instead of a lambda.

Expects a function(){} instead of a () => {}
