### ISSUE TITLE
TypeError: infoDict.has is not a function

### ISSUE THREAD

**Issue by ElModdy** [modesty/pdf2json#186]
TypeError: infoDict.has is not a function
    at PDFDocument.get documentInfo [as documentInfo] (eval at <anonymous> (/home/usr/repos/Work1/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4638:24)
    at LocalPdfManager_ensure [as ensure] (eval at <anonymous> (/home/usr/repos/Work1/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:32503:22)
    at LocalPdfManager.BasePdfManager_ensureModel [as ensureModel] (eval at <anonymous> (/home/usr/repos/Work1/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:32442:19)
    at Object.parseSuccess [as onResolve] (eval at <anonymous> (/home/usr/repos/Work1/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:27104:38)
    at Object.runHandlers (eval at <anonymous> (/home/usr/repos/Work1/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:864:35)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
An error occurred while parsing the PDF: infoDict.has is not a function
An error occurred while parsing the PDF: infoDict.has is not a function

**Comment by modesty** [comment]
please upload your testing PDF

**Comment by paulroth3d** [comment]
Hi @modesty / @ElModdy, I'm unsure if this is the same issue, but I think it is.

I put an example pdf in a gist here:

https://gist.github.com/paulroth3d/9b47d9edc776f7243582da65961bbd79

I did notice, that the problem may have something to do with multiple pages in pdfs.

Once I extracted out the page I wanted from the PDF, then the issue went away.
