### ISSUE TITLE
iam getting  following error/warning   while iam uploading the pdf and parsing it

### ISSUE THREAD

**Issue by vikrantb53** [modesty/pdf2json#210]
DownloadPdf   form here ---->   https://www.dropbox.com/s/wyei3bo4tsz107k/NYC_DHS_IsolationDischarge.pdf?dl=0

error in uploading pdf parsePage error:An error occurred while rendering the page 1:
Warning: name token is longer than allowed by the spec: 134:
Error: Warning: name token is longer than allowed by the spec: 134
    at error (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:195:9)
    at Lexer_getName [as getName] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:24512:9)
    at Lexer_getObj [as getObj] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:24584:23)
    at Parser_shift [as shift] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:24038:32)
    at Parser_getObj [as getObj] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:24081:14)
    at XRef_fetch [as fetch] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:5788:29)
    at XRef_fetchIfRef [as fetchIfRef] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:5699:19)
    at Dict_get [as get] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4759:28)
    at getDefaultAppearance (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:3517:39)
    at WidgetAnnotation.Annotation (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:3562:23)
    at new WidgetAnnotation (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:3767:16)
    at Function.Annotation_fromRef [as fromRef] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:3724:22)
    at Page.get annotations [as annotations] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4424:37)
    at LocalPdfManager_ensure [as ensure] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:32503:22)
    at Page_getOperatorList [as getOperatorList] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4352:43)
    at Object.eval [as onResolve] (eval at <anonymous> (/home/vikrant/projects/opencitylabs_test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:27397:14)
Mongoose: organisations.find({ orgLocations: { '$exists': true } }, { fields: {} })

**Comment by vikrantb53** [comment]
my package .json file is 


{
  "name": "abd",
  "version": "0.0.0",
  "private": true,
  "main": "app.js",
  "scripts": {
    "start": "node ./bin/start export NODE_ENV=development",
    "test": "mocha --recursive './test/*Test.js' --compilers js:babel-core/register"
  },
  "dependencies": {
    "@babel/core": "^7.3.4",
    "ag-grid-community": "^23.2.0",
    "ag-grid-enterprise": "^23.2.0",
    "angular-lazyload": "^0.3.2",
    "angular-ui-grid": "^4.8.3",
    "angularjs-daterangepicker": "^1.1.5",
    "async": "^2.6.0",
    "async-waterfall": "^0.1.5",
    "body-parser": "~1.16.0",
    "bower": "^1.8.4",
    "chartjs-plugin-datalabels": "^0.7.0",
    "config": "^3.2.2",
    "cookie-parser": "~1.4.3",
    "country-data": "0.0.31",
    "crypto-js": "^3.1.9-1",
    "d3": "^5.15.1",
    "debug": "~2.6.0",
    "ejs": "^2.5.5",
    "exceljs": "^3.9.0",
    "express": "~4.14.1",
    "express-session": "^1.15.3",
    "geolocator": "^2.1.3",
    "gulp-htmlmin": "^5.0.1",
    "gulp-rename": "^1.4.0",
    "gulp-uglifyes": "^0.1.3",
    "json-stringify-safe": "^5.0.1",
    "jspdf": "^1.5.3",
    "languages": "^0.1.3",
    "mailgun-js": "^0.13.1",
    "md-date-range-picker": "^0.8.4",
    "moment": "^2.24.0",
    "mongoose": "^4.9.0",
    "morgan": "~1.7.0",
    "multer": "^1.4.2",
    "ng-image-cache": "^0.2.0",
    "node-xlsx": "^0.15.0",
    "nodemailer": "^4.1.3",
    "oauth2orize": "^1.11.0",
    "objectid": "^3.2.1",
    "passport": "^0.3.2",
    "passport-http": "^0.3.0",
    "passport-http-bearer": "^1.0.1",
    "passport-local": "^1.0.0",
    "passport-oauth2-client-password": "^0.1.2",
    "path": "^0.12.7",
    "pdf2json": "^1.2.0",
    "pdffiller": "0.0.10",
    "pdfjs-dist": "^2.4.456",
    "read-excel-file": "^4.0.6",
    "request": "^2.85.0",
    "save": "^2.3.2",
    "shortid": "^2.2.14",
    "simple-statistics": "^7.0.2",
    "stylus": "^0.54.5",
    "twilio": "^3.47.0",
    "underscore-node": "^0.1.2",
    "usa-states": "0.0.5",
    "uuid": "^3.3.2",
    "winston": "^3.2.1",
    "winston-mongodb": "^5.0.0"
  },
  "devDependencies": {
    "@babel/standalone": "^7.1.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^7.1.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-stage-0": "^6.22.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "eslint": "^3.1.1",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-mocha": "^4.8.0",
    "eslint-plugin-react": "^6.10.0",
    "gulp": "^3.9.1",
    "gulp-babel": "^8.0.0",
    "gulp-clean-css": "^3.10.0",
    "gulp-cli": "^1.2.2",
    "gulp-concat": "^2.6.0",
    "gulp-ng-annotate": "^1.1.0",
    "gulp-ng-html2js": "^0.2.0",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-uglify": "^1.2.0",
    "gulp-watch": "^4.3.4"
  }
}

**Comment by vikrantb53** [comment]
observatins:
======================================
