### ISSUE TITLE
Cannot read property 'vertical' of undefined

### ISSUE THREAD

**Issue by jonnypa** [modesty/pdf2json#244]
Hi,

I'm getting this error while uploading a document with acroforms. 
Using the same document, sometimes the upload is successful, sometimes this error occurs:

```
Debug: internal, implementation, error
     TypeError: Uncaught error: Cannot read property 'vertical' of undefined
     at CanvasGraphics_showText [as showText] (eval at <anonymous> (/***/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:41083:27)
     at CanvasGraphics_executeOperatorList [as executeOperatorList] (eval at <anonymous> (/***/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:40566:27)
     at InternalRenderTask__next [as _next] (eval at <anonymous> (/***/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:43560:39)
     at InternalRenderTask__continue [as _continue] (eval at <anonymous> (/***/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:43552:14)
     at ontimeout (timers.js:436:11)
     at tryOnTimeout (timers.js:300:5)
     at listOnTimeout (timers.js:263:5)
     at Timer.processTimers (timers.js:223:10)
```

This is the code 

```javascript
return new Promise(async (resolve, reject) => { 
  [...]
const pdfParser = new PDFParser();
    pdfParser.on("pdfParser_dataError", errData => {
      resolve(errData.parserError
   });
    pdfParser.on("pdfParser_dataReady", async pdfData => { 
      resolve(pdfData)
    });
   pdfParser.loadPDF(pdfPath);
})
```

Other details: 

Node: v10.24.1
npm: 6.14.12
pdf2json: 1.2.4

Can someone help me? 
Thanks in advance

**Comment by jonnypa** [comment]
Thank you for this fix! When do you plan to release it in a NPM package?
