### ISSUE TITLE
Receiving unsupported encryption algorithm when pdf encryption is 256 AES

### ISSUE THREAD

**Issue by AvaJay** [modesty/pdf2json#246]
### Information
Node: v14.18.0
npm: v6.14.15
pdf2json: v1.2.5
pdfreader: v1.2.11

We are using pdfreader to verify the contents of a downloaded pdf, it was working perfectly until recently when our pdf encryption changed from MD5 to AES

### Issue
When pdfreader calls on pdf2json to convert our pdf to json format we are receiving this error 
```
Error: unsupported encryption algorithm
    at error (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:195:9)
    at new CipherTransformFactory (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:6708:7)
    at XRef_parse [as parse] (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:5282:24)
    at PDFDocument_setup [as setup] (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4613:17)
    at PDFDocument_parse [as parse] (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4497:12)
    at LocalPdfManager_ensure [as ensure] (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:32506:24)
    at LocalPdfManager.BasePdfManager_ensureModel [as ensureModel] (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:32442:19)
    at Object.eval [as onResolve] (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:27133:22)
    at Object.runHandlers (eval at <anonymous> (/Users/ava/runtime/node_modules/pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:864:35)
    at ontimeout (timers.js:436:11)
An error occurred while parsing the PDF: unsupported encryption algorithm
{ parserError:
   'An error occurred while parsing the PDF: unsupported encryption algorithm' }
```
This is line 64 of pdf.js that is failing `_pdfjsFiles.forEach( (fieldName, idx, arr) => _fileContent += fs.readFileSync(_basePath + fieldName, 'utf8') ); ` I've tried playing around with the encoding type but was unsuccessful.  Any chance of a workaround or a fix for this issue?  Thanks a lot!

**Comment by Jule-** [comment]
@modesty do you plan to support AES256? Is that something difficult to achieve?

**Comment by Jule-** [comment]
This issue is linked to #126 (and #44), depending on [pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist) package instead of an outdated dump will fix this issue and maybe a lot more.
