### ISSUE TITLE
MozBlobBuilder is not defined

### ISSUE THREAD

**Issue by craig-walker-orennia** [modesty/pdf2json#247]
When running from the CLI I get this error:

```
% node ./node_modules/pdf2json/pdf2json.js -f file.pdf 

pdf2json@1.2.5 [https://github.com/modesty/pdf2json]
Transcoding report.pdf to - file.json
Info: about to load PDF file file.pdf
Info: Load PDF file status:Success!
Warning: Setting up fake worker.
Info: PDF loaded. pagesCount = 10
Info: start to parse page:1
Warning: Unhandled rejection: ReferenceError: MozBlobBuilder is not defined
ReferenceError: MozBlobBuilder is not defined
    at Object.createBlob (eval at <anonymous> (node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:1104:12)
    at Object.createObjectURL (eval at <anonymous> (node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:1112:24)
    at JpegStream_getIR [as getIR] (eval at <anonymous> (node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:25575:18)
    at PartialEvaluator_buildPaintImageXObject [as buildPaintImageXObject] (eval at <anonymous> (node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:7120:64)
    at PartialEvaluator_getOperatorList [as getOperatorList] (eval at <anonymous> (node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:7464:24)
    at Object.eval [as onResolve] (eval at <anonymous> (node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4348:26)
    at Object.runHandlers (eval at <anonymous> (node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:864:35)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

Looking through the code I see this:
```
/* globals Cmd, ColorSpace, Dict, MozBlobBuilder, Name, PDFJS, Ref, URL */
```
...so it's clear that it's assuming that `MozBlobBuilder` exists, but I don't see any place where it would be defined. 

The only Google hits I could find refer to a deprecated and removed API:
* https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/18#domapis
* https://bugzilla.mozilla.org/show_bug.cgi?id=744907

**Comment by zql365747776** [comment]
> es6class is merged to master, close.

did this issues fix in 1.3.1?
