### ISSUE TITLE
version 1.3.1 fails to compile: unexpected token '(' on pdfparser.js:53

### ISSUE THREAD

**Issue by jnchaba** [modesty/pdf2json#250]
![pdf2json_issue](https://user-images.githubusercontent.com/35639052/139110992-e6b469fd-5eb9-49a5-af61-bc692925fca3.png)

I tried this on node v14, v16 and v6.9.4. It presented in all 3.

Workaround: uninstalling version 1.3.1 and reinstalling to 1.2.5 resolved this for me.

**Comment by modesty** [comment]
please pull `es6class` branch and try again

**Comment by Atom1er** [comment]
I just installed this package today and getting the same/similar error:

`node_modules/pdf2json/pdfparser.js:54
[0]     #onPDFJSParseDataReady(data) {
[0]                           ^
[0] 
[0] SyntaxError: Unexpected token '('
[0]     at wrapSafe (internal/modules/cjs/loader.js:1070:16)
[0]     at Module._compile (internal/modules/cjs/loader.js:1120:27)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
[0]     at Module.load (internal/modules/cjs/loader.js:1000:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
[0]     at Module.require (internal/modules/cjs/loader.js:1042:19)
[0]     at require (internal/modules/cjs/helpers.js:77:18)
[0]     at Object.<anonymous> (/Users/thomasminoungou/Documents/GitHub/levy/server.js:13:19)
[0]     at Module._compile (internal/modules/cjs/loader.js:1156:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)`

**Comment by stack4world** [comment]
I met the same issue.

        #onPDFJSParseDataReady(data) {
                              ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    ...

**Comment by yuis-ice** [comment]
The same issue here

**Comment by emretapci** [comment]
> please pull `es6class` branch and try again

Checked out `es6class` branch, still the same error.

**Comment by irgipaulius** [comment]
Same issue here. Using OPs workaround: 

```
npm i --save-exact pdf2json@1.2.5
```

**Comment by AnselK** [comment]
The same issue here

**Comment by reyanRaj** [comment]
Same issue here

**Comment by modesty** [comment]
although class private instance methods were support by node since v14.21.3, [Class static initialization blocks](https://github.com/tc39/proposal-class-static-block) support requires node@v17.9.1.
pdf2json [requires node@v18.12.1](https://github.com/modesty/pdf2json/blob/master/package.json#L49), upgrade node version should solve the problem.
