### ISSUE TITLE
npm ERR! code ERR_INVALID_ARG_TYPE during install pdf2json as subdependency

### ISSUE THREAD

**Issue by StanislavKharchenko** [modesty/pdf2json#251]
The following issue occurs with ver 1.2.5 and latest 1.3.X during install pdf2json as subdependency from main dependency:
```
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined
```

Not reproduced with 1.2.4

Steps to reproduce:
1. NodeJS: v14 (or v16);
2. NPM v7 (or v8);
3. Have your own package PKG1 which has pdf2json: 1.2.5 as dependency;
4. From another package PKG2, make command: npm i PKG1.

Problem:

```
628 verbose stack TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
628 verbose stack     at new NodeError (internal/errors.js:322:7)
628 verbose stack     at validateString (internal/validators.js:124:11)
628 verbose stack     at relative (path.js:492:5)
628 verbose stack     at C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1069:21
628 verbose stack     at Array.map (<anonymous>)
628 verbose stack     at C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1067:66
628 verbose stack     at Array.map (<anonymous>)
628 verbose stack     at Arborist.[rollbackMoveBackRetiredUnchanged] (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1067:8)
628 verbose stack     at Arborist.[reifyPackages] (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:231:31)
628 verbose stack     at async Arborist.reify (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:151:5)
```

**Comment by StanislavKharchenko** [comment]
And have the similar issue while using 2.0 version.
Could someone from maintainers check?

**Comment by modesty** [comment]
node 18.x+ is required, please try it again with 3.1.2
