### ISSUE TITLE
Running on Electron "Uncaught Error: No PDFJS.workerSrc specified"

### ISSUE THREAD

**Issue by whitef0x0** [modesty/pdf2json#68]
For some reason when I run pdf2json on my electron app I get "Uncaught Error: No PDFJS.workerSrc specified". 

FYI:  I tried setting workerSrc to pdf.worker.js but that won't solve it. It just brings up another error,

**Comment by whitef0x0** [comment]
@modesty

**Comment by modesty** [comment]
how did you run pdf2json? 
if you run it via cmd line, or as a web service, this error should not occur.

**Comment by whitef0x0** [comment]
@modesty I ran in an electron app.

**Comment by modesty** [comment]
pdj2json is designed to run outside browser, and never tested with embedded browser (as in electron framework). 3 options here: 
* invoke cmd line to run pdf2json from your app
* set globalScope.PDFJS.disableWorker to be true
* set PDFJS.workerSrc = Worker

**Comment by wilsonchandra** [comment]
@whitef0x0 @modesty It turns out that I have the same problem too. Any luck on running pdf2json in electron? Thanks...

**Comment by lanwin** [comment]
It works when you run it in the main process and not in any of the rendering process, and use the remote api to exchange data between them.

**Comment by wilsonchandra** [comment]
@lanwin Thanks for your heads up. That works for me too...

**Comment by wilsonchandra** [comment]
@parzel Thanks for the explanation. I used it that way too...

**Comment by suparpat** [comment]
using
`let PDFParser = require('electron').remote.require('pdf2json')`
instead of 
`let PDFParser = require('pdf2json')`

worked for me.
Thank you!

**Comment by sunilrebel** [comment]
@suparpat  - can you please tell what can be done in `nwjs` app?
I'm getting the same issue, most probably it'll be the same solution. Unable to load `pdf2json` module correctly in `nwjs` app.

**Comment by samuel-mrodrigues** [comment]
> 

It worked for me during development with electron:serve, after bundling the program with electron:build, opening the executable would cause the module not being found.

I did the correcy way and moved my code to the main proccess.

**Comment by victor-rds** [comment]
Sorry for necro postin, but I got the same error when running with Deno 2.x, no electron, no browser, just a single typescript file.

> error: Uncaught (in worker "") (in promise) Error: Load Failed: /pdf-scraper/tmp/freq-2023-08.pdf - Error: No PDFJS.workerSrc specified
>     at Object.Oe [as p2jerror] (file:///pdf-scraper/node_modules/.deno/pdf2json@3.1.4/node_modules/pdf2json/dist/pdfparser.js:1:26848)
>     at hi.loadPDF (file:///pdf-scraper/node_modules/.deno/pdf2json@3.1.4/node_modules/pdf2json/dist/pdfparser.js:1:921773)
>     at eventLoopTick (ext:core/01_core.js:175:7)

```js
{
  message: "Uncaught (in promise) Error: Load Failed: /pdf-scraper/tmp/freq-2023-08.pdf - Error: No PDFJS.workerSrc specified",
  fileName: "file:///pdf-scraper/node_modules/.deno/pdf2json@3.1.4/node_modules/pdf2json/dist/pdfparser.js",
  lineNumber: 1,
  columnNumber: 26848
}
```

**Comment by cherryfoot** [comment]
> Sorry for necro postin, but I got the same error when running with Deno 2.x, no electron, no browser, just a single typescript file.
> 
> > error: Uncaught (in worker "") (in promise) Error: Load Failed: /pdf-scraper/tmp/freq-2023-08.pdf - Error: No PDFJS.workerSrc specified
> > at Object.Oe [as p2jerror] (file:///pdf-scraper/node_modules/.deno/pdf2json@3.1.4/node_modules/pdf2json/dist/pdfparser.js:1:26848)
> > at hi.loadPDF (file:///pdf-scraper/node_modules/.deno/pdf2json@3.1.4/node_modules/pdf2json/dist/pdfparser.js:1:921773)
> > at eventLoopTick (ext:core/01_core.js:175:7)
> 
> {
>   message: "Uncaught (in promise) Error: Load Failed: /pdf-scraper/tmp/freq-2023-08.pdf - Error: No PDFJS.workerSrc specified",
>   fileName: "file:///pdf-scraper/node_modules/.deno/pdf2json@3.1.4/node_modules/pdf2json/dist/pdfparser.js",
>   lineNumber: 1,
>   columnNumber: 26848
> }

Did you ever figure out how to get around this issue?

**Comment by adarshmadrecha** [comment]
Runs fine with Node but fails in Bun and Deno.

```js
import PDFParser from "pdf2json";
const pdfParser = new PDFParser();
const filePath = 'sample_pdf/6071107.pdf'
pdfParser.loadPDF(filePath);
```

```bash
Error: No PDFJS.workerSrc specified
      at Ee (\node_modules\pdf2json\dist\pdfparser.js:1:28759)
      at loadPDF (\node_modules\pdf2json\dist\pdfparser.js:1:924046)
```

**Comment by modesty** [comment]
tried to fix it in [scratch/fixWorkerDenoBun](https://github.com/modesty/pdf2json/tree/scratch/fixWorkerDenoBun), please give it a shot
