### ISSUE TITLE
agenda throws error when working with pdf2json

### ISSUE THREAD

**Issue by jonscyriac** [modesty/pdf2json#72]
after update to 1.1.5 from 0.7.1, when i use pdf2json

`'TypeError: Cannot read property \'update\' of undefined',
     '    at unlockJobs (/home/jons/***/***/node_modules/sails-hook-jobs/node_modules/agenda/lib/agenda.js:319:11)',
     '    at Agenda.stop (/home/jons/***/***/node_modules/sails-hook-jobs/node_modules/agenda/lib/agenda.js:247:14)',
     '    at Sails.stopServer (/home/***/***/node_modules/sails-hook-jobs/index.js:14:12)',
     '    at emitNone (events.js:72:20)',
     '    at Sails.emit (events.js:166:7)',
     '    at Sails.emitter.emit (/home/***/***/node_modules/sails/lib/app/private/after.js:50:11)'`

this agenda is a dependancy of sails-hook-jobs
sails 0.12.3
node 4.4.7
ubuntu 14.04
agenda 0.6.28

**Comment by modesty** [comment]
not clear about the context. pdf2json has no dependency on neither "sails" nor "agenda", is this relevant?
