### ISSUE TITLE
Having a hard time getting started

### ISSUE THREAD

**Issue by jesmitty** [modesty/pdf2json#84]
Let me preface this by saying I don't know what I am doing with pdf2json. I want to translate a pdf file to a json file and installed your package on windows (also have cygwin). First I tried it at a command line utility here:

		C:\data\E2\JSON\node_modules\pdf2json>node pdf2json.js -f test\pdf\fd\form\f1040.pdf
		C:\data\E2\JSON\node_modules\pdf2json\lib\p2jcmd.js:3
		let nodeUtil = require("util"),
		^^^
		SyntaxError: Unexpected strict mode reserved word
			at exports.runInThisContext (vm.js:73:16)
			at Module._compile (module.js:443:25)
			at Object.Module._extensions..js (module.js:478:10)
			at Module.load (module.js:355:32)
			at Function.Module._load (module.js:310:12)
			at Module.require (module.js:365:17)
			at require (module.js:384:17)
			at Object.<anonymous> (C:\data\E2\JSON\node_modules\pdf2json\pdf2json.js:3:14)
			at Module._compile (module.js:460:26)
			at Object.Module._extensions..js (module.js:478:10)

Perhaps it had something to do with the warning I got with the install when I did:
			
			C:\data\E2\JSON>npm install pdf2json -g
			npm WARN engine pdf2json@1.1.6: wanted: {"node":">=4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
			C:\Users\jeff.smith\AppData\Roaming\npm\pdf2json -> C:\Users\jeff.smith\AppData\Roaming\npm\node_modules\pdf2jso
			n\bin\pdf2json
			pdf2json@1.1.6 C:\Users\jeff.smith\AppData\Roaming\npm\node_modules\pdf2json
			
Do you know what I am doing wrong?

**Comment by modesty** [comment]
install Node v4.5 (you have 0.12) will make 'getting started' smooth.
