### ISSUE TITLE
 events.js:141       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by wanghaisheng** [modesty/pdf2json#93]
```
node version:v4.4.1
pdf2json version v1.1.7
```
code is like this
```

var fs = require('fs'),
    nodeEvents = require("events"),
    _ = require('lodash'),
    PFParser = require("pdf2json");


function pdfParserPromise(fileName, fromBuffer) {
    var promise = new(nodeEvents.EventEmitter);

     var pdfParser = new PFParser();

     pdfParser.on("pdfParser_dataReady", function(evtData) {
         if ((!!evtData) && (!!evtData.data)) {
             promise.emit('success', evtData.data);
         }
         else {
             console.log("1111"+evtData.data)
             promise.emit('error', new Error("undefined"));
         }
     });

     pdfParser.on("pdfParser_dataError", function(evtData) {
                      console.log("2222")

         promise.emit('error', evtData.data);
     });

     var pdfFilePath = __dirname + "/data/" + fileName + ".pdf";
     if (fromBuffer) {
       pdf = fs.readFileSync(pdfFilePath);
       pdfParser.parseBuffer(pdf);
     } else {
       pdfParser.loadPDF(pdfFilePath);
     }

     return promise;
}    


function checkResult_parseStatus(err, stat, fileName) {
    if(_.isNull(err) || _.isUndefined(err)){
        console.log(fileName + " PDF 解析出错!")
        return 2001
    }else{
        console.log(fileName + " PDF 成功解析!")

    }


    if(_.isObject(stat)){
        console.log(fileName + " PDF 结果应该是 JS 对象 而非静态对象!")
        return 2001
    }else{
        console.log(fileName + " PDF 成功解析!")

    }
    // assert(_.isNull(err) || _.isUndefined(err), fileName + " has errors!");    // We have no error
    // assert(_.isObject(stat), fileName + " parsing result should be JS object");// We have a stat object
}

function checkResult_mainFields(parsedData, fileName) {

    if(_.has(parsedData, "Agency")){
        console.log(fileName + " parsing error: doesn't have Agency object")

    }else{
        console.log(fileName + " parsing success: have Agency object")

    }
    if(_.has(parsedData, "Id")){
        console.log(fileName + " parsing error: doesn't have Id object")

    }else{
        console.log(fileName + " parsing success: have Id object")

    }
    if(_.has(parsedData, "Pages")){
        console.log(fileName + " parsing error: doesn't have Pages object")

    }else{
        console.log(fileName + " parsing success: have Pages object")

    }
    if(_.has(parsedData, "Width")){
        console.log(fileName + " parsing error: doesn't have Width object")

    }else{
        console.log(fileName + " parsing success: have Width object")

    }
    // assert(_.has(parsedData, "Agency"), fileName + " parsing error: doesn't have Agency object");
    // assert(_.has(parsedData, "Id"), fileName + " parsing error: doesn't have Id object");
    // assert(_.has(parsedData, "Pages"), fileName + " parsing error: doesn't have Pages object");
    // assert(_.has(parsedData, "Width"), fileName + " parsing error: doesn't have Width object");
}

function checkResult_pageCount(Pages, count, fileName) {
    if(_.isArray(Pages)){
        console.log(fileName + " parsing error: doesn't have Pages array")

    }else{
        console.log(fileName + " parsing success: have Pages array")

    }
    if(Pages.length === count){
        console.log(fileName + " parsing error:  Pages array is empty")

    }else{
        console.log(fileName + " parsing success:  Pages array is not empty")

    }
    // assert(_.isArray(Pages), fileName + " parsing error: doesn't have Pages array");
    // assert(Pages.length === count, fileName + " parsing error: Pages array is empty");
}

function checkResult_pageContent(Pages, fileName) {
    _.each(Pages, function(page, index, list) {
        if(_.has(page, "Height")){
        console.log(fileName + " parsing error: current page doesn't have Height object")

    }else{
        console.log(fileName + " parsing success: current page  have Height object")

    }                

        if(_.has(page, "Height")){
        console.log(fileName + " parsing error: current page doesn't have Height object")

    }else{
        console.log(fileName + " parsing success: current page  have Height object")

    }         

        if(_.has(page, "HLines")){
        console.log(fileName + " parsing error: current page doesn't have HLines object")

    }else{
        console.log(fileName + " parsing success: current page  have HLines object")

    }         

        if(_.has(page, "VLines")){
        console.log(fileName + " parsing error: current page doesn't have VLines object")

    }else{
        console.log(fileName + " parsing success: current page  have VLines object")

    }         
        if(_.has(page, "Fills")){
        console.log(fileName + " parsing error: current page doesn't have Fills object")

    }else{
        console.log(fileName + " parsing success: current page  have Fills object")

    }     
        if(_.has(page, "Texts")){
        console.log(fileName + " parsing error: current page doesn't have Texts object")

    }else{
        console.log(fileName + " parsing success: current page  have Texts object")

    }     
        // assert(_.has(page, "Height"), fileName + " page " + index + " : doesn't have Height field");
        // assert(_.has(page, "HLines"), fileName + " page " + index + " : doesn't have HLines object");
        // assert(_.has(page, "VLines"), fileName + " page " + index + " : doesn't have VLines object");
        // assert(_.has(page, "Fills"), fileName + " page " + index + " : doesn't have Fills object");
        // assert(_.has(page, "Texts"), fileName + " page " + index + " : doesn't have Texts object");
    });
}

var promise = pdfParserPromise("2", false);
console.log(promise)
```
full error
```

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: undefined
    at PdfParser.<anonymous> (/home/xxx/dockerfiles-repo/docker-for-fun/docker-alpine/projects/pdf-parser/pdf2htmlEX/ubuntu/html-parser/js-based/htmlparser2/demo3.js:36:36)
    at emitOne (events.js:77:13)
    at PdfParser.emit (events.js:169:7)
    at PdfParser._onPDFJSParseDataReady (/home/xxx/dockerfiles-repo/docker-for-fun/docker-alpine/projects/pdf-parser/pdf2htmlEX/ubuntu/html-parser/js-based/htmlparser2/node_modules/pdf2json/pdfparser.js:23:9)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at /home/xxx/dockerfiles-repo/docker-for-fun/docker-alpine/projects/pdf-parser/pdf2htmlEX/ubuntu/html-parser/js-based/htmlparser2/node_modules/pdf2json/lib/pdf.js:250:38
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

```

**Comment by wanghaisheng** [comment]
fix by 
```
'use strict';

// let fs = require('fs'),
//     PDFParser = require("pdf2json");
//      _ = require('lodash');
// let pdfParser = new PDFParser();

// pdfParser.on("pdfParser_dataError", errData => console.error(errData.parserError) );
// pdfParser.on("pdfParser_dataReady", pdfData => {
//     // fs.writeFile("1.json", JSON.stringify(pdfData));
//   pdfData = JSON.stringify(pdfData)


// });

// pdfParser.loadPDF("1.pdf");


var fs = require('fs'),
nodeEvents = require("events"),
_ = require('lodash'),
PFParser = require("pdf2json");


function pdfParserPromise(fileName, fromBuffer) {
    var promise = new(nodeEvents.EventEmitter);
    
    var pdfParser = new PFParser();
    
    pdfParser.on("pdfParser_dataReady", function(evtData) {
                 console.log("PDF 解析成功"+JSON.stringify(evtData) )

                 promise.emit('success', evtData);
                 
                 //  if ((!!evtData) && (!!evtData.data)) {
                 //      promise.emit('success', evtData.data);
                 //  }
                 //  else {
                 //      promise.emit('error', new Error());
                 //  }
                 });
    
    pdfParser.on("pdfParser_dataError", function(evtData) {
                 promise.emit('error', evtData.data);
                 });
    
    var pdfFilePath = __dirname + "/data/" + fileName + ".pdf";
    
    if (fromBuffer) {
        pdf = fs.readFileSync(pdfFilePath);
        pdfParser.parseBuffer(pdf);
    } else {
        pdfParser.loadPDF(pdfFilePath);
    }
    
    return promise;
}

function checkResult_parseStatus(err, fileName) {
    if(_.isNull(err) || _.isUndefined(err)){
        console.log(fileName + " PDF 解析出错!")
        return 2001
    }else{
        console.log(fileName + " PDF 成功解析!")
        
    }
    
    
    // if(_.isObject(stat)){
    //     console.log(fileName + " PDF 结果应该是 JS 对象 而非静态对象!")
    //     return 2002
    // }else{
    //     console.log(fileName + " PDF 成功解析!")
    
    // }
    // assert(_.isNull(err) || _.isUndefined(err), fileName + " has errors!");    // We have no error
    // assert(_.isObject(stat), fileName + " parsing result should be JS object");// We have a stat object
}

function checkResult_mainFields(parsedData, fileName) {
    
    if(_.has(parsedData, "Agency")){
        console.log(fileName + " parsing error: doesn't have Agency object")
        
    }else{
        console.log(fileName + " parsing success: have Agency object")
        
    }
    if(_.has(parsedData, "Id")){
        console.log(fileName + " parsing error: doesn't have Id object")
        
    }else{
        console.log(fileName + " parsing success: have Id object")
        
    }
    if(_.has(parsedData, "Pages")){
        console.log(fileName + " parsing error: doesn't have Pages object")
        
    }else{
        console.log(fileName + " parsing success: have Pages object")
        
    }
    if(_.has(parsedData, "Width")){
        console.log(fileName + " parsing error: doesn't have Width object")
        
    }else{
        console.log(fileName + " parsing success: have Width object")
        
    }
    
}

function checkResult_pageCount(Pages, count, fileName) {
    if(_.isArrayLikeObject(Pages)){
        console.log(fileName + " parsing error: doesn't have Pages array")
        
    }else{
        console.log(fileName + " parsing success: have Pages array")
        
    }
    if(_.size(Pages) === count){
        console.log(fileName + " parsing error:  Pages array is empty")
        
    }else{
        console.log(fileName + " parsing success:  Pages array is not empty"+_.size(Pages))
        
    }
    
}

function checkResult_pageContent(Pages, fileName) {
    _.each(Pages, function(page, index, list) {
           if(_.has(page, "Height")){
           console.log(fileName + " page " + index + " : have Height field")
           
           }else{
           console.log(fileName + " page " + index + " : doesn't have Height field")
           
           }
           
           if(_.has(page, "HLines")){
           console.log(fileName + " page " + index + " : have HLines field")
           
           }else{
           console.log(fileName + " page " + index + " : doesn't have HLines field")
           
           }
           
           if(_.has(page, "VLines")){
           console.log(fileName + " page " + index + " : have VLines field")
           
           }else{
           console.log(fileName + " page " + index + " : doesn't have HLines field")
           
           }
           if(_.has(page, "Fills")){
           console.log(fileName + " page " + index + " : have Fills field")
           
           }else{
           console.log(fileName + " page " + index + " : doesn't have Fills field")
           
           }
           if(_.has(page, "Texts")){
           console.log(fileName + " page " + index + " : have Texts field")
           
           }else{
           console.log(fileName + " page " + index + " : doesn't have Texts field")
           
           }
           
           });
}

var promise = pdfParserPromise("1", false);

promise.on('error', function(err) {
           // console.log("PDF 解析出错")
           checkResult_parseStatus(err,"2")
           });

promise.on('success', function(evtData) {
//            console.log("PDF 解析成功"+JSON.stringify(evtData) )
           checkResult_mainFields(evtData, "2");
           
           
           //   for (var i = 0; i < evtData.formImage.Pages.length; i++){
           //     console.log("---"+typeof( evtData.formImage.Pages)+"--"+ evtData.formImage.Pages[i])
           //             checkResult_pageCount(evtData.formImage.Pages, 0,"1");
           
           //             checkResult_pageContent(evtData.formImage.Pages, "1");
           
           // }
           
           _.each(evtData,function(value){
                  
                  // var jsondata = JSON.stringify(evtData)
                  var o =value["Pages"]
                  //死活转不了array 始终数据类型是object
                  var  Pages =_.toArray(o);
//                  console.log("---"+typeof(Pages)+"--"+JSON.stringify(Pages))
                  _.each(Pages,function(value){
                         
                         checkResult_pageCount(Pages, 0,"2");
                         checkResult_pageContent(Pages, "2");
                         
                         }
                         
                         )
                  
                  // console.log("PDF 解析成功111"+JSON.stringify(Pages) )
                  
                  }
                  
                  )
           
           
           
           
           });


```
